/*Lalith Vaishnav Elangovan*/

#include <stdio.h>
#include <math.h>

//Here we use recursion to create the factorial function
int factorial(int n){
  if (n==0) 
    return 1;
  else
  return (n*factorial(n-1));
}

//Here we create the choose function from the given formula
int choose(int n, int r) {
    return (factorial(n)/(factorial(r)*factorial(n-r)));
}

//Here we create the triangle function 
void triangle (int rows){
 for (int rowNo = 0; rowNo <= (rows-1); rowNo++)
 {
// This part of the code uses a for loop to create the spaces from the left

   for (int spaces = (rows-rowNo)*3-4; spaces >= 0; spaces--)
   {
     printf(" ");
   }

// This prints the number generated by the choose function, and uses -3d to assign a given amount of space and the spaces
// after assign the 3 space gap    
   for (int number = 0; number <= rowNo; number++)
   {
     printf("%-3d   ",choose(rowNo,number));
   }
   printf("\n");
 } 
}
int main(){
  int rows;
//This do while loop is to ensure that the printf keeps running until the input value is <0 or >=14
  do
  {
    printf("Enter the number of rows: ");
    scanf("%d",&rows);
    if (rows>=14||rows<0)
       break;
    triangle(rows);
  } while (rows>=0 && rows<14);
  return 0;
}



